#pragma once
#include "wet1util.h"
//#include "AbstractAVL.h"
//#include "IndexAble.h"
//#include "NonOwningHorseAVL.h"
//#include "NonOwningHerdAVL.h"
//#include "OwningHorseAVL.h"
//#include "OwningHerdAVL.h"
#include "Horse.h"
#include "Herd.h"
//#include "HorseMap.h"
//#include "HorseTree.h"
//#include "TraceAble.h"
#include "AVLTree.h"
//#include "LinkedList.h"
#include <cassert>
#include <new>
#include <iostream>
//#include "Pair.h"
//#include "HorseList.h"